apiVersion: apps/v1
kind: Deployment
metadata:
  name: sj123

spec:
  replicas: 3
  selector:
    matchLabels:
      app: sj123
  template:
    metadata:
      labels:
        app: sj123

    spec:
      containers:
        - name: sj123
          image: icr.io/sj123/ccr
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
