apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccr

spec:
  replicas: 3
  selector:
    matchLabels:
      app: ccr
  template:
    metadata:
      labels:
        app: ccr

    spec:
      containers:
        - name: ccr
          image: icr.io/sj123/ccr
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
